export const actiontypes = {
  ADD_ACCOUNT: 'ADD_ACCOUNT',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  TOOGLE_DRAWER: 'TOOGLE_DRAWER',
  SET_CATEGORIES: 'SET_CATGORIES',
  ADD_IMAGE: 'ADD_IMAGE',
  SET_SUBJECTS: 'SET_SUBJECTS',
  SET_IMAGES: 'SET_IMAGES',
  SET_CHECKED: 'SET_CHECKED',
  TOOGLE_DARK: 'TOOGLE_DARK',
  CREATE_QUIZ: 'CREATE_QUIZ',
  ADD_QUESTION: 'ADD_QUESTION',
  UPDATE_ANSWER: 'UPDATE_ANSWER'
}

//export const baseURL = 'https://projectapi.ml/'

export const baseURL = 'http://localhost:8080/'
