export const actiontypes = {
  ADD_ACCOUNT: 'ADD_ACCOUNT',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  TOOGLE_DRAWER: 'TOOGLE_DRAWER',
  SET_CATEGORIES: 'SET_CATGORIES',
  ADD_SUBJECT_IMAGE: 'ADD_SUBJECT_IMAGE',
  DELETE_SUBJECT: 'DELETE_SUBJECT',
  ADD_SUBJECT: 'ADD_SUBJECT',
  SET_SUBJECTS: 'SET_SUBJECTS',
  SET_IMAGES: 'SET_IMAGES',
  SET_CHECKED: 'SET_CHECKED',
  TOOGLE_DARK: 'TOOGLE_DARK',
  CREATE_QUIZ: 'CREATE_QUIZ',
  ADD_QUESTION: 'ADD_QUESTION',
  SELECT_OPTION: 'SELECT_OPTION',
  DELETE_QUIZ: 'DELETE_QUIZ',
  COMPLETE_QUIZ: 'COMPLETE_QUIZ',
  ADD_QUESTION_IMAGE: 'ADD__QUESTION_IMAGE',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  ADD_CATEGORY: 'ADD_CATEGORY',
  ADD_CATEGORY_IMAGE: 'ADD_CAT_IMAGE',
  ADD_IMAGE: 'ADD_IMAGE',
  ADD_OR_UPDATE_TEST: 'ADD_OR_UPDATE_TEST',
  SELECT_ANSWER: 'SELECT_ANSWER',
  SUBMIT_TEST: 'SUBMIT_TEST'
}
// export const baseURL = 'https://projectapi.ml/'
export const baseURL = 'http://localhost:8080/'
