export const actiontypes = {
  ADD_ACCOUNT: 'ADD_ACCOUNT',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  TOOGLE_DRAWER: 'TOOGLE_DRAWER',
  SET_CATEGORIES: 'SET_CATGORIES',
  ADD_IMAGE: 'ADD_IMAGE',
  SET_SUBJECTS: 'SET_SUBJECTS',
  SET_IMAGES: 'SET_IMAGES',
  SET_CHECKED: 'SET_CHECKED'
}

export const baseURL = 'https://projectapi.ml/'
